import type { CardData } from "../types/CardTypes";

export const CARD_DATABASE: Record<string, CardData> = {
  SENTINEL_01: {
    id: "SENTINEL_01",
    type: "MONSTER",
    nameKey: "Sentinela de Ferro",
    descriptionKey: "Um guardião ancestral que nunca dorme.",
    manaCost: 2,
    atk: 15,
    def: 20,
    imageKey: "monster_sentinel",
    width: 300,
    height: 400,
  },
  SENTINEL_02: {
    id: "SENTINEL_02",
    type: "EFFECT_MONSTER",
    nameKey: "Sentinela de Ferro",
    descriptionKey: "Um guardião ancestral que nunca dorme.",
    manaCost: 2,
    atk: 12,
    def: 20,
    imageKey: "monster_sentinel",
    width: 300,
    height: 400,
  },
  FIRE_BALL: {
    id: "FIRE_BALL",
    type: "SPELL",
    nameKey: "Bola de Fogo",
    descriptionKey: "Causa 10 de dano a todos os inimigos.",
    effects: { type: "BURN", value: 10, targetSide: "OPPONENT" },
    manaCost: 2,
    imageKey: "spell_fireball",
    width: 300,
    height: 400,
  },
  // DRAW_CARD: {
  //   id: "DRAW_CARD",
  //   type: "SPELL",
  //   nameKey: "Pote da ganância",
  //   descriptionKey: "Compre 1 carta.",
  //   effects: { type: "DRAW_CARD", value: 1, targetSide: "OWNER" },
  //   manaCost: 2,
  //   imageKey: "spell_fireball",
  //   width: 300,
  //   height: 400,
  // },
  // CHANGE_POS: {
  //   id: "CHANGE_POS",
  //   type: "SPELL",
  //   nameKey: "Virada de jogo",
  //   descriptionKey: "Escolha um monstro no campo. Mude a posição do alvo",
  //   effects: { type: "CHANGE_POS", targetSide: "OPPONENT" },
  //   manaCost: 1,
  //   imageKey: "spell_fireball",
  //   width: 300,
  //   height: 400,
  // },
  DESTROY_SPELL: {
    id: "DESTROY_SPELL",
    type: "SPELL",
    nameKey: "Tornado",
    descriptionKey: "Escolha uma magia no campo, destrua a carta",
    effects: { type: "DESTROY", targetSide: "OPPONENT", targetType: "SPELL" },
    manaCost: 1,
    imageKey: "spell_fireball",
    width: 300,
    height: 400,
  },
  BOOST_ATK: {
    id: "BOOST_ATK",
    type: "SPELL",
    nameKey: "Fúria",
    descriptionKey: "Aumente o ataque do monstro em 15 pontos.",
    effects: { type: "BOOST_ATK", value: 15, targetSide: "BOTH" },
    manaCost: 1,
    imageKey: "spell_fireball",
    width: 300,
    height: 400,
  },
  // BOOST_DEF: {
  //   id: "BOOST_DEF",
  //   type: "SPELL",
  //   nameKey: "Escudo",
  //   descriptionKey: "Aumente a defesa do monstro em 15 pontos.",
  //   effects: { type: "BOOST_DEF", value: 15, targetSide: "BOTH" },
  //   manaCost: 1,
  //   imageKey: "spell_fireball",
  //   width: 300,
  //   height: 400,
  // },
  // REVIVE_SPELL: {
  //   id: "REVIVE_SPELL",
  //   type: "SPELL",
  //   nameKey: "Reviver magia",
  //   descriptionKey:
  //     "Restaure uma carta mágica do seu cemitério, devolva-a pra sua mão.",
  //   effects: { type: "REVIVE", targetSide: "OWNER" },
  //   manaCost: 1,
  //   imageKey: "spell_fireball",
  //   width: 300,
  //   height: 400,
  // },
  REVIVE_MONSTER: {
    id: "REVIVE_MONSTER",
    type: "SPELL",
    nameKey: "Reviver monstro",
    descriptionKey: "Revive um monstro do cemitério e o envia ao campo.",
    effects: { type: "REVIVE", targetSide: "BOTH", targetType: "MONSTER" },
    manaCost: 1,
    imageKey: "spell_fireball",
    width: 300,
    height: 400,
  },
  // NERF_ATK: {
  //   id: "NERF_ATK",
  //   type: "SPELL",
  //   nameKey: "Memento",
  //   descriptionKey: "Diminua o ataque do monstro em 15 pontos.",
  //   effects: { type: "NERF_ATK", value: 15, targetSide: "BOTH" },
  //   manaCost: 1,
  //   imageKey: "spell_fireball",
  //   width: 300,
  //   height: 400,
  // },
  BOUNCE: {
    id: "BOUNCE",
    type: "SPELL",
    nameKey: "Alavanca",
    descriptionKey: "Selecione um monstro no campo. Retorne o alvo à mão.",
    effects: { type: "BOUNCE", targetSide: "OPPONENT", targetType: "MONSTER" },
    manaCost: 1,
    imageKey: "",
    width: 300,
    height: 400,
  },
  // DARK_TRAP: {
  //   id: "DARK_TRAP",
  //   type: "TRAP",
  //   nameKey: "Armadilha Sombria",
  //   descriptionKey: "Imobiliza o próximo monstro atacante.",
  //   manaCost: 1,
  //   imageKey: "trap_darkness",
  //   width: 300,
  //   height: 400,
  // },
};
